artifact_location: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/485708261959657622
creation_time: 1702063898480
experiment_id: '485708261959657622'
last_update_time: 1702063898480
lifecycle_stage: active
name: job-profile-prediction
