aliases: []
creation_timestamp: 1702076316510
current_stage: None
description: null
last_updated_timestamp: 1702076316510
name: xgboost
run_id: 92ed66d742664ef78606066f1ed74a8c
run_link: null
source: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/463203211872186726/92ed66d742664ef78606066f1ed74a8c/artifacts/model
status: READY
status_message: null
storage_location: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/463203211872186726/92ed66d742664ef78606066f1ed74a8c/artifacts/model
user_id: null
version: 2
