aliases: []
creation_timestamp: 1702075981841
current_stage: None
description: null
last_updated_timestamp: 1702075981841
name: logistic_regression
run_id: a658fec9c539468c8e7115668a53c5e6
run_link: null
source: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/463203211872186726/a658fec9c539468c8e7115668a53c5e6/artifacts/model
status: READY
status_message: null
storage_location: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/463203211872186726/a658fec9c539468c8e7115668a53c5e6/artifacts/model
user_id: null
version: 2
