aliases: []
creation_timestamp: 1702068826438
current_stage: None
description: null
last_updated_timestamp: 1702068826438
name: xgboost
run_id: 7396a38eb17e42898bc5586415caf600
run_link: null
source: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/778414887343833243/7396a38eb17e42898bc5586415caf600/artifacts/model
status: READY
status_message: null
storage_location: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/778414887343833243/7396a38eb17e42898bc5586415caf600/artifacts/model
user_id: null
version: 1
