aliases: []
creation_timestamp: 1702064359137
current_stage: None
description: null
last_updated_timestamp: 1702064359137
name: xgboost
run_id: 37cac0d546294bf0af484399c4f22d22
run_link: null
source: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/485708261959657622/37cac0d546294bf0af484399c4f22d22/artifacts/model
status: READY
status_message: null
storage_location: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/485708261959657622/37cac0d546294bf0af484399c4f22d22/artifacts/model
user_id: null
version: 1
