channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - packaging==23.1
  - pandas==2.0.3
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.11.3
  - typing==3.7.4.3
  - xgboost==2.0.2
name: mlflow-env
