aliases: []
creation_timestamp: 1702063900707
current_stage: None
description: null
last_updated_timestamp: 1702063900707
name: logistic_regression
run_id: 577aab9fc4e64888974f43a13b2b7df7
run_link: null
source: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/485708261959657622/577aab9fc4e64888974f43a13b2b7df7/artifacts/model
status: READY
status_message: null
storage_location: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/485708261959657622/577aab9fc4e64888974f43a13b2b7df7/artifacts/model
user_id: null
version: 1
