aliases: []
creation_timestamp: 1702068811935
current_stage: None
description: null
last_updated_timestamp: 1702068811935
name: logistic_regression
run_id: 4ed585893a244f9e8d5b2d6fdf2d4c7a
run_link: null
source: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/778414887343833243/4ed585893a244f9e8d5b2d6fdf2d4c7a/artifacts/model
status: READY
status_message: null
storage_location: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/778414887343833243/4ed585893a244f9e8d5b2d6fdf2d4c7a/artifacts/model
user_id: null
version: 1
