artifact_location: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/826012750732074976
creation_time: 1701627635656
experiment_id: '826012750732074976'
last_update_time: 1701627635656
lifecycle_stage: active
name: job-profile-prediction
