artifact_location: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/463203211872186726
creation_time: 1702075934380
experiment_id: '463203211872186726'
last_update_time: 1702075934380
lifecycle_stage: active
name: job-profile-prediction
