artifact_location: /Users/Aya/Tech-Job-profile-prediction-dsProject/notebooks/../mlflow/778414887343833243
creation_time: 1702068808729
experiment_id: '778414887343833243'
last_update_time: 1702068808729
lifecycle_stage: active
name: job-profile-prediction
